name: yc-training-unit-test
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
      - integration
    paths:
      - src/workshop/core/data_engineering/*
      - src/workshop/core/evaluating/*
      - src/workshop/core/training/*
      - src/workshop/env/*
      - .github/workflows/yc_training_unit_test.yml

jobs:
  unit-test:
    runs-on: ubuntu-latest
    environment: 'dev'
    steps:
      - name: check out repo
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade twine
      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: src/workshop/env
          mode: dev
      - name: show env variables
        run: |
          echo "group: ${{ env.group }}"
          echo "workspace: ${{ env.workspace }}"
          echo "location: ${{ env.location }}"
          echo "compute: ${{ env.compute }}"  
          echo "endpoint: ${{ env.endpoint }}"  
      - name: AZ Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_IBIZACA }} # SETUP: replace MY_AZURE_CREDENTIALS with your own secret name
      - name: Install AZ ML and tools
        run: | 
          az extension add -n ml -y
          az configure --defaults group=${{ env.group }} workspace=${{ env.workspace }} location=${{ env.location }} 
      - name: run training and model validation
        run: |
         az ml job create -s -f src/workshop/core/pipelines/training_pipeline.yml --set compute=${{ env.compute }}

  pull-request:
    if: ${{ success() }}
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:      
      - name: Create Pull Request to Integration
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.IBIZACA_GITHUB_SECRET }} #setup: provide your github secret name
          head: ${{ github.ref }}
          base: integration
          title: "An automatically created PR by successful unit test to integration"

